Locale should be "en" instead of "en:English"
Fixes an exception like:

      (localisation_id, voice) = localisation_id_voice.split(":")
  ValueError: too many values to unpack (expected 2)
  Traceback (most recent call last):
    File "./libs/chesstalker/chesstalker.py", line 588, in <module>
      chesstalker.say_text("Hello chess-lovers")
    File "./libs/chesstalker/chesstalker.py", line 494, in say_text
      cmd = self.voice_command.replace("$(TEXT)", "\"" + text + "\"")